#!/usr/bin/env bash

for prog in zenity openvpn3; do
	which $prog > /dev/null

	if [[ ! $? -eq 0 ]]; then
		zenity --error --text="$prog is not installed" || printf "$prog is not installed\n"
		exit 1
	fi
done

main () {
	zenity --list \
		--title='OpenVPN3 Configuration Manager' \
		--ok-label='Connect' \
		--cancel-label='Exit' \
		--extra-button='Configure' \
		--column='Configuration Path' \
		$(openvpn3 configs-list | grep /net/openvpn/v3/configuration/)
}

configure () {
	zenity --list \
		--title='OpenVPN3 Configuration Manager' \
		--ok-label='Remove' \
		--cancel-label='Back' \
		--extra-button='Import' \
		--column='Configuration Path' \
		$(openvpn3 configs-list | grep /net/openvpn/v3/configuration/)
}

import () {
	declare target=$(zenity --file-selection)
	declare basename=$(basename $target)

	declare configs=$(openvpn3 configs-list | grep /net/openvpn/v3/configuration/)

	if [[ $configs == *"$basename"* && $configs != '' && $basename != '' ]]; then
		zenity --info --text='This config has already been imported'
	elif [[ $configs != '' && $basename != '' ]]; then
		openvpn3 config-import --persistent --config $target
	fi
}

remove () {
	openvpn3 config-remove --force --config-path $action
}

session_start () {
	openvpn3 session-start --config-path $action
}

while :; do
	declare action=$(main)

	if [[ $action == 'Configure' ]]; then
		while :; do
			declare action=$(configure)

			if [[ $action == 'Import' ]]; then
				import
			elif [[ $action == '/net/openvpn/v3/configuration/'* ]]; then
				remove
			else
				break
			fi
		done
	elif [[ $action == '/net/openvpn/v3/configuration/'* ]]; then
		session_start
	else
		exit 0
	fi
done
